"updates":
- "directory": "/"
  "groups":
    "github-actions":
      "patterns":
      - "*"
  "open-pull-requests-limit": 10
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
    "time": "04:00"
- "directory": "/packages/nixos-options-split"
  "groups":
    "rust":
      "patterns":
      - "*"
  "open-pull-requests-limit": 10
  "package-ecosystem": "rust"
  "schedule":
    "interval": "daily"
    "time": "04:00"
"version": 2
