name: "Publish docsets to gh pages"
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build nix docsets and upload"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake update
        working-directory: pages
      - run: nix build "./pages"
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/

  deploy:
    if: always() && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v4
